### ISSUE TITLE
pyfilesystem can sometimes fail at startup and make the whole app crash

### ISSUE THREAD

**Issue by gokudomatic** [gokudomatic/cobiv#1]

**Comment by gokudomatic** [comment]
[INFO   ] [Logger      ] Record log in C:\Users\edwin\.kivy\logs\kivy_17-10-01_25.txt
INFO:kivy:[Logger      ] Record log in C:\Users\edwin\.kivy\logs\kivy_17-10-01_25.txt
[INFO   ] [Kivy        ] v1.10.0
INFO:kivy:[Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
INFO:kivy:[Python      ] v2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
[INFO   ] [Factory     ] 194 symbols loaded
INFO:kivy:[Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
INFO:kivy:[Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <thread> for socket
INFO:kivy:[OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
INFO:kivy:[Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
INFO:kivy:[GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
INFO:kivy:[GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
INFO:kivy:[GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <4.4.0 - Build 20.19.15.4531>
INFO:kivy:[GL          ] OpenGL version <4.4.0 - Build 20.19.15.4531>
[INFO   ] [GL          ] OpenGL vendor <Intel>
INFO:kivy:[GL          ] OpenGL vendor <Intel>
[INFO   ] [GL          ] OpenGL renderer <Intel(R) HD Graphics 5500>
INFO:kivy:[GL          ] OpenGL renderer <Intel(R) HD Graphics 5500>
[INFO   ] [GL          ] OpenGL parsed version: 4, 4
INFO:kivy:[GL          ] OpenGL parsed version: 4, 4
[INFO   ] [GL          ] Shading version <4.40 - Build 20.19.15.4531>
INFO:kivy:[GL          ] Shading version <4.40 - Build 20.19.15.4531>
[INFO   ] [GL          ] Texture max size <16384>
INFO:kivy:[GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
INFO:kivy:[GL          ] Texture max units <32>
[INFO   ] [Shader      ] fragment shader: <WARNING: 0:7: '' :  #version directive missing>
INFO:kivy:[Shader      ] fragment shader: <WARNING: 0:7: '' :  #version directive missing>
[INFO   ] [Shader      ] vertex shader: <WARNING: 0:7: '' :  #version directive missing>
INFO:kivy:[Shader      ] vertex shader: <WARNING: 0:7: '' :  #version directive missing>
[INFO   ] [Window      ] auto add sdl2 input provider
INFO:kivy:[Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
INFO:kivy:[Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
INFO:kivy:[Text        ] Provider: sdl2
DEBUG:yapsy:PluginFileLocator walks (recursively) into directory: C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:component.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:component.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:entity.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:entity.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:hud.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:hud.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:view.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:view.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:ImageSet.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:ImageSet.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:slide.kv is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:cursor.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:cursor.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:Session.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:Session.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:PluginFileLocator found a candidate:
    C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\core\session\session.yapsy-plugin
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:thumbloader.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:ThumbLoader.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:PluginFileLocator found a candidate:
    C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\core\thumbloader\thumbloader.yapsy-plugin
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:datasource.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:datasource.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:sqliteds.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:Sqliteds.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:PluginFileLocator found a candidate:
    C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\database\datasources\sqlite\sqliteds.yapsy-plugin
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:sqlitedb.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:SqliteDb.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:PluginFileLocator found a candidate:
    C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\database\sqlitedb\sqlitedb.yapsy-plugin
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:abstractsearchstrategy.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:abstractsearchstrategy.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:customtablestrategy.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:customtablestrategy.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:defaultstrategy.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:defaultstrategy.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:searchmanager.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:searchmanager.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:sqlitefunctions.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:sqlitefunctions.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:progresshud.kv is not a valid plugin for strategy info_ext
DEBUG:yapsy:progresshud.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:ProgressHud.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:PluginFileLocator found a candidate:
    C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\hud_components\progresshud\progresshud.yapsy-plugin
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:sidebar.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:Sidebar.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:PluginFileLocator found a candidate:
    C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\hud_components\sidebar\sidebar.yapsy-plugin
DEBUG:yapsy:statusbar.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:StatusBar.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:PluginFileLocator found a candidate:
    C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\hud_components\sidebar\statusbar.yapsy-plugin
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:labelwidget.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:LabelWidget.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:PluginFileLocator found a candidate:
    C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\hud_components\sidebar\widgets\labelwidget.yapsy-plugin
DEBUG:yapsy:separatorwidget.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:SeparatorWidget.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:PluginFileLocator found a candidate:
    C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\hud_components\sidebar\widgets\separatorwidget.yapsy-plugin
DEBUG:yapsy:tagswidget.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:TagsWidget.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:PluginFileLocator found a candidate:
    C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\hud_components\sidebar\widgets\tagswidget.yapsy-plugin
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:tagreader.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:tagreader.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:tagcrcreader.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:TagCrcReader.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:PluginFileLocator found a candidate:
    C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\io\tag-crc\tagcrcreader.yapsy-plugin
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:browser.kv is not a valid plugin for strategy info_ext
DEBUG:yapsy:browser.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:Browser.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:PluginFileLocator found a candidate:
    C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\views\browser\browser.yapsy-plugin
DEBUG:yapsy:eolitem.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:eolitem.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:item.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:item.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:ThumbnailImage.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:ThumbnailImage.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:help.kv is not a valid plugin for strategy info_ext
DEBUG:yapsy:help.rst is not a valid plugin for strategy info_ext
DEBUG:yapsy:PluginFileLocator found a candidate:
    C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\views\help\help.yapsy-plugin
DEBUG:yapsy:helpview.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:HelpView.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:viewer.kv is not a valid plugin for strategy info_ext
DEBUG:yapsy:viewer.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:Viewer.pyc is not a valid plugin for strategy info_ext
DEBUG:yapsy:PluginFileLocator found a candidate:
    C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\views\viewer\viewer.yapsy-plugin
DEBUG:yapsy:__init__.py is not a valid plugin for strategy info_ext
DEBUG:yapsy:__init__.pyc is not a valid plugin for strategy info_ext
[INFO   ] [VideoGstplayer] Using Gstreamer 1.10.2.0
INFO:kivy:[VideoGstplayer] Using Gstreamer 1.10.2.0
[INFO   ] [Video       ] Provider: gstplayer
INFO:kivy:[Video       ] Provider: gstplayer
DEBUG:__main__:plugin ready : <yapsy_loaded_plugin_session_0.Session object at 0x032433D0>
DEBUG:__main__:plugin ready : <yapsy_loaded_plugin_sqlite_ds_0.Sqliteds object at 0x032C5E10>
DEBUG:__main__:plugin ready : <yapsy_loaded_plugin_browser_0.Browser object at 0x03B73458>
DEBUG:__main__:plugin ready : <yapsy_loaded_plugin_viewer_0.Viewer object at 0x0A189E68>
DEBUG:__main__:plugin ready : <yapsy_loaded_plugin_sidebar_0.Sidebar object at 0x03B3BB20>
DEBUG:__main__:plugin ready : <yapsy_loaded_plugin_tagcrc_0.TagCrcReader object at 0x03B6C970>
 Exception in thread Thread-1:
WARNING:kivy:stderr: Exception in thread Thread-1:
 Traceback (most recent call last):
WARNING:kivy:stderr: Traceback (most recent call last):
 Traceback (most recent call last):
WARNING:kivy:stderr: Traceback (most recent call last):
   File "C:/Users/edwin/Apps/python/workspace/cobiv/cobiv/MainApp.py", line 119, in <module>
WARNING:kivy:stderr:   File "C:/Users/edwin/Apps/python/workspace/cobiv/cobiv/MainApp.py", line 119, in <module>
   File "C:\Python27\Lib\threading.py", line 801, in __bootstrap_inner
WARNING:kivy:stderr:   File "C:\Python27\Lib\threading.py", line 801, in __bootstrap_inner
     Cobiv().run()
WARNING:kivy:stderr:     Cobiv().run()
     self.run()
WARNING:kivy:stderr:     self.run()
   File "C:\Python27\lib\site-packages\kivy\app.py", line 802, in run
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\kivy\app.py", line 802, in run
   File "C:\Python27\Lib\threading.py", line 754, in run
WARNING:kivy:stderr:   File "C:\Python27\Lib\threading.py", line 754, in run
     root = self.build()
WARNING:kivy:stderr:     root = self.build()
     self.__target(*self.__args, **self.__kwargs)
WARNING:kivy:stderr:     self.__target(*self.__args, **self.__kwargs)
   File "C:/Users/edwin/Apps/python/workspace/cobiv/cobiv/MainApp.py", line 75, in build
WARNING:kivy:stderr:   File "C:/Users/edwin/Apps/python/workspace/cobiv/cobiv/MainApp.py", line 75, in build
   File "C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\database\sqlitedb\SqliteDb.py", line 505, in _threaded_updatedb
WARNING:kivy:stderr:   File "C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\database\sqlitedb\SqliteDb.py", line 505, in _threaded_updatedb
     plugin.plugin_object.ready()
WARNING:kivy:stderr:     plugin.plugin_object.ready()
     to_add, to_remove = self._update_get_diff(repo_id, repo_path, recursive)
WARNING:kivy:stderr:     to_add, to_remove = self._update_get_diff(repo_id, repo_path, recursive)
   File "C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\database\sqlitedb\SqliteDb.py", line 440, in ready
WARNING:kivy:stderr:   File "C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\database\sqlitedb\SqliteDb.py", line 440, in ready
   File "C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\database\sqlitedb\SqliteDb.py", line 537, in _update_get_diff
WARNING:kivy:stderr:   File "C:\Users\edwin\Apps\python\workspace\cobiv\cobiv\modules\database\sqlitedb\SqliteDb.py", line 537, in _update_get_diff
     fs = open_fs(path)
WARNING:kivy:stderr:     fs = open_fs(path)
     repo_fs = open_fs(path)
WARNING:kivy:stderr:     repo_fs = open_fs(path)
   File "C:\Python27\lib\site-packages\fs\opener\registry.py", line 179, in open_fs
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\fs\opener\registry.py", line 179, in open_fs
   File "C:\Python27\lib\site-packages\fs\opener\registry.py", line 179, in open_fs
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\fs\opener\registry.py", line 179, in open_fs
     default_protocol=default_protocol
WARNING:kivy:stderr:     default_protocol=default_protocol
     default_protocol=default_protocol
WARNING:kivy:stderr:     default_protocol=default_protocol
   File "C:\Python27\lib\site-packages\fs\opener\registry.py", line 138, in open
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\fs\opener\registry.py", line 138, in open
   File "C:\Python27\lib\site-packages\fs\opener\registry.py", line 138, in open
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\fs\opener\registry.py", line 138, in open
     opener = self.get_opener(protocol)
WARNING:kivy:stderr:     opener = self.get_opener(protocol)
     opener = self.get_opener(protocol)
WARNING:kivy:stderr:     opener = self.get_opener(protocol)
   File "C:\Python27\lib\site-packages\fs\opener\registry.py", line 74, in get_opener
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\fs\opener\registry.py", line 74, in get_opener
   File "C:\Python27\lib\site-packages\fs\opener\registry.py", line 74, in get_opener
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\fs\opener\registry.py", line 74, in get_opener
     None
WARNING:kivy:stderr:     None
     None
WARNING:kivy:stderr:     None
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 725, in iter_entry_points
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 725, in iter_entry_points
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 725, in iter_entry_points
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 725, in iter_entry_points
     entries = dist.get_entry_map(group)
WARNING:kivy:stderr:     entries = dist.get_entry_map(group)
     entries = dist.get_entry_map(group)
WARNING:kivy:stderr:     entries = dist.get_entry_map(group)
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2656, in get_entry_map
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2656, in get_entry_map
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2656, in get_entry_map
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2656, in get_entry_map
     self._get_metadata('entry_points.txt'), self
WARNING:kivy:stderr:     self._get_metadata('entry_points.txt'), self
     self._get_metadata('entry_points.txt'), self
WARNING:kivy:stderr:     self._get_metadata('entry_points.txt'), self
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2394, in parse_map
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2394, in parse_map
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2394, in parse_map
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2394, in parse_map
     maps[group] = cls.parse_group(group, lines, dist)
WARNING:kivy:stderr:     maps[group] = cls.parse_group(group, lines, dist)
     maps[group] = cls.parse_group(group, lines, dist)
WARNING:kivy:stderr:     maps[group] = cls.parse_group(group, lines, dist)
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2372, in parse_group
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2372, in parse_group
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2372, in parse_group
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2372, in parse_group
     ep = cls.parse(line, dist)
WARNING:kivy:stderr:     ep = cls.parse(line, dist)
     ep = cls.parse(line, dist)
WARNING:kivy:stderr:     ep = cls.parse(line, dist)
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2354, in parse
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2354, in parse
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2354, in parse
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2354, in parse
     return cls(res['name'], res['module'], attrs, extras, dist)
WARNING:kivy:stderr:     return cls(res['name'], res['module'], attrs, extras, dist)
     return cls(res['name'], res['module'], attrs, extras, dist)
WARNING:kivy:stderr:     return cls(res['name'], res['module'], attrs, extras, dist)
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2275, in __init__
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2275, in __init__
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2275, in __init__
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2275, in __init__
     self.extras = Requirement.parse(("x[%s]" % ','.join(extras))).extras
     self.extras = Requirement.parse(("x[%s]" % ','.join(extras))).extras
WARNING:kivy:stderr:     self.extras = Requirement.parse(("x[%s]" % ','.join(extras))).extras
WARNING:kivy:stderr:     self.extras = Requirement.parse(("x[%s]" % ','.join(extras))).extras
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2935, in parse
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2935, in parse
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2935, in parse
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2935, in parse
     req, = parse_requirements(s)
WARNING:kivy:stderr:     req, = parse_requirements(s)
     req, = parse_requirements(s)
WARNING:kivy:stderr:     req, = parse_requirements(s)
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2883, in parse_requirements
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2883, in parse_requirements
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2883, in parse_requirements
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2883, in parse_requirements
     yield Requirement(line)
WARNING:kivy:stderr:     yield Requirement(line)
     yield Requirement(line)
WARNING:kivy:stderr:     yield Requirement(line)
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2892, in __init__
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2892, in __init__
   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2892, in __init__
WARNING:kivy:stderr:   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2892, in __init__
     raise RequirementParseError(str(e))
WARNING:kivy:stderr:     raise RequirementParseError(str(e))
     raise RequirementParseError(str(e))
WARNING:kivy:stderr:     raise RequirementParseError(str(e))
 pkg_resources.RequirementParseError: Invalid requirement, parse error at "']'"
WARNING:kivy:stderr: pkg_resources.RequirementParseError: Invalid requirement, parse error at "']'"
 RequirementParseError: Invalid requirement, parse error at "']'"
WARNING:kivy:stderr: RequirementParseError: Invalid requirement, parse error at "']'"
 
WARNING:kivy:stderr:
